version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rikka
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongodb_data:/data/db

  rikka:
    depends_on:
      - mongodb
    build: .
    restart: always
